### ISSUE TITLE
Change `risk_score` to risk ratio

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/lead-model#9]
We've had internal discussion on the best representation of risk and the way to communicate that through the `risk_score` response. Because `risk_score_notes` will contain specific instructions, I think we're in agreement that using risk ratio in `risk_score` is useful.

I believe this work would be done in the model, but let me know if this belong somewhere else in the stack.

**Comment by tomschenkjr** [comment]
Just following-up on this to see about progress. Thanks!

**Comment by RaedMan** [comment]
risk_score  (numeric value)
risk_score_notes  **HIGH RISK: Refer for lead paint visual home inspection to Chicago Department of Public Health at 312-747-LEAD(5323)**

risk_score  (numeric value)
risk_score_notes  **LOW RISK: Discuss lead exposure prevention anticipatory guidance.**

risk_score  NULL
risk_score_notes  **HIGH BLL DETECTED IN LABS: Model not run. Review labs.**

**Comment by geneorama** [comment]
Thank you for the language, I'm going to move that update to the runner.

At this time we are not going to do a relative risk score, so I'm closing this issue.  If we change course we can reopen this issue or start a new one and reference this one.
